version: '3.4'
services:
  typeorm_issue_test:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
